name: Deploy PreTeXt to GitHub Pages

on:
  push:
    branches:
      - main

# Set explicit permissions for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install PreTeXt
      run: |
        pip install --upgrade pip
        pip install pretext
    
    - name: Build PreTeXt book
      run: |
        pretext build web
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./output/web
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4